name: yumpro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.0.0
  image_picker: ^0.8.4+4
  file_picker: ^4.2.7
  http: ^1.2.1
  shared_preferences: ^2.0.9
  fluttertoast: ^8.2.5
  flutter_branch_sdk: ^5.0.0
  mixpanel_flutter: ^2.2.0
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
